export const WEATHER_CODES = {
  0: { text: "Clear Sky", icon: "sun" },
  1: { text: "Mainly Clear", icon: "cloud-sun" },
  2: { text: "Partly Cloudy", icon: "cloud-sun" },
  3: { text: "Overcast", icon: "cloud" },
  45: { text: "Fog", icon: "cloud" },
  48: { text: "Fog", icon: "cloud" },
  51: { text: "Light Drizzle", icon: "cloud-rain" },
  53: { text: "Drizzle", icon: "cloud-rain" },
  55: { text: "Heavy Drizzle", icon: "cloud-rain" },
  61: { text: "Light Rain", icon: "cloud-rain" },
  63: { text: "Rain", icon: "cloud-rain" },
  65: { text: "Heavy Rain", icon: "cloud-rain" },
  80: { text: "Rain Showers", icon: "cloud-rain" },
  81: { text: "Heavy Rain Showers", icon: "cloud-rain" },
  82: { text: "Violent Rain Showers", icon: "cloud-rain" },
  95: { text: "Thunderstorm", icon: "cloud-lightning" },
  96: { text: "Thunderstorm with Hail", icon: "cloud-lightning" },
  99: { text: "Heavy Thunderstorm", icon: "cloud-lightning" },
};
